const shopActionTypes = {
  FETCHING_COLLECTIONS_START: "FETCHING_COLLECTIONS_START",
  FETCHING_COLLECTIONS_SUCCESS: "FETCHING_COLLECTIONS_SUCCESS",
  FETCHING_COLLECTIONS_FAILUER: "FETCHING_COLLECTIONS_FAILUER",
};

export default shopActionTypes;
