const userActionTypes = {
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILUER: "SIGNIN_FAILUER",
  EMAIL_SIGNIN_START: "EMAIL_SIGNIN_START",
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGNOUT_START: "SIGNOUT_START",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNOUT_FAILUER: "SIGNOUT_FAILUER",
  SIGNUP_START: "SIGNUP_START",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILUER: "SIGNUP_FAILUER",
};

export default userActionTypes;
